[package]
name = "wom-rpg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
llm-chain = "0.9.0"
llm-chain-openai = "0.9.0"
termimad = "0.23.0"
tokio = { version = "1.28.0", features = ["rt"] }
